local Plug = vim.fn['plug#']

vim.call('plug#begin', '~/.config/nvim/plugged')

Plug('nvim-lualine/lualine.nvim')
Plug('nvim-tree/nvim-web-devicons')
Plug('nvim-tree/nvim-tree.lua')
Plug('navarasu/onedark.nvim')
Plug('folke/tokyonight.nvim', {branch = 'main' })
Plug('goolord/alpha-nvim')
Plug('eandrju/cellular-automaton.nvim')
Plug('norcalli/nvim-colorizer.lua')
Plug('lukas-reineke/indent-blankline.nvim')

Plug('nvim-treesitter/nvim-treesitter', {['do'] = ':TSUpdate'})
Plug('zbirenbaum/copilot.lua')
Plug('nvim-telescope/telescope.nvim', {tag = '0.1.1' })
Plug('nvim-lua/plenary.nvim')
Plug('ggandor/leap.nvim')
Plug('tpope/vim-fugitive')
Plug('kylechui/nvim-surround')
Plug('numToStr/Comment.nvim')
Plug('nvim-telescope/telescope-project.nvim')
Plug('lewis6991/gitsigns.nvim')
Plug('alvan/vim-closetag')
Plug('neoclide/coc.nvim', {branch = 'release'})
Plug('christoomey/vim-tmux-navigator')
Plug('preservim/vimux')
Plug('michaeljsmith/vim-indent-object')
Plug('akinsho/bufferline.nvim')

vim.call('plug#end')

require('plugins/alpha')
require('plugins/autopair')
require('plugins/bufferline')
require('plugins/blankline')
require('plugins/cellular-automaton')
require('plugins/colorizer')
require('plugins/comment')
require('plugins/copilot')
require('plugins/fugitive')
require('plugins/gitsigns')
require('plugins/leap')
require('plugins/lualine')
require('plugins/nvim-web-devicons')
require('plugins/surround')
require('plugins/telescope')
require('plugins/tmux')
require('plugins/treesitter')
require('plugins/nvim-tree')
require('plugins/theme')
require('plugins/coc')
